# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'APOD' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for APOD
  pod 'DGZoomableImageView', :git => 'https://github.com/donggyushin/DGZoomableImageView.git'

  target 'APODTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'APODUITests' do
    # Pods for testing
  end

end
